export const DOCUMENT_TYPES = [
    "PDF DNI FRENTE",
    "PDF DNI DORSO",
    "PDF TITULO SECUNDARIO O DE GRADO",
    "PDF TITULO DE COACH",
    "PDF CURRICULUM VITAE",
    "PDF PARTIDA DE NACIMINENTO",
    "FOTO TIPO CARNET - FONDO BLANCO",
];
